[package]
name = "lenv-rs"
version = "0.1.0"
authors = [
    "Ty Hopp"
]
description = "Manage symlinks from a root file to multiple destinations"
edition = "2021"
license = "MIT"
include = [
    "Cargo.toml",
    "LICENSE",
    "README.md",
    "src/"
]
repository = "https://github.com/tyhopp/lenv-ports"
keywords = [
    "symlink",
    "env",
    "monorepo",
    "cli",
    "wasi"
]
categories = [
    "command-line-utilities",
    "config",
    "development-tools"
]

[dependencies]
wasmtime = "25.0.1"
wasmtime-wasi = "25.0.1"

[[bin]]
name = "lenv"
path = "src/main.rs"
